
"use client";

import React, { useEffect, useMemo, useRef, useState } from "react";
import Split from "react-split";
import { toast } from "sonner";
import { Download, Copy, Share2, Image as ImageIcon, Settings2, Code2, LayoutPanelLeft, Moon, Sun } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeRaw from "rehype-raw";
import rehypeSanitize, { defaultSchema } from "rehype-sanitize";
import Prism from "prismjs";
import "prismjs/components/prism-markup";
import "prismjs/components/prism-clike";
import "prismjs/components/prism-markup-templating";
import "prismjs/components/prism-javascript";
import "prismjs/components/prism-typescript";
import "prismjs/components/prism-json";
import "prismjs/components/prism-bash";
import "prismjs/components/prism-python";
import "prismjs/plugins/line-numbers/prism-line-numbers";
import "prismjs/plugins/line-numbers/prism-line-numbers.css";
import "prismjs/themes/prism-tomorrow.css";
import { createClient } from "@supabase/supabase-js";

const CARBON_BG = {
  onedark: "bg-[#282c34]",
  midnight: "bg-[#0e1116]",
  dracula: "bg-[#282a36]",
} as const;
type CarbonKey = keyof typeof CARBON_BG;

const fira = "'Fira Code', ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace";

const getEnvSafe = (key: string) => {
  try { if (typeof process !== "undefined" && (process as any).env?.[key]) return (process as any).env[key] as string; } catch {}
  const g: any = typeof window !== "undefined" ? window : globalThis;
  return g?.POLISHPASTE_ENV?.[key];
};
const cn = (...a: any[]) => a.filter(Boolean).join(" ");

const LANGUAGE_LIST = ["typescript","javascript","python","bash","json","markdown","css","html","tsx","jsx"];

export default function CanvasPage() {
  const [isDark, setIsDark] = useState(true);
  const [mode, setMode] = useState<"card"|"design">("card");
  const [raw, setRaw] = useState(`export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};`);
  const [lang, setLang] = useState("typescript");
  const [theme, setTheme] = useState<CarbonKey>("onedark");
  const [fontSize, setFontSize] = useState(16);
  const [filename, setFilename] = useState("snippet");
  const previewRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLDivElement>(null);
  const exportRef = useRef<HTMLDivElement>(null);

  const cloudUrl = "https://sljntkzrgtyzuaobarol.supabase.co"
  const cloudKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsam50a3pyZ3R5enVhb2Jhcm9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MTExMDQsImV4cCI6MjA3MDI4NzEwNH0.jsw0_SUDJmUl_6t0avAhakzBTY8It3D59TksIioFsFY"

  useEffect(() => { document.documentElement.classList.toggle("dark", isDark); }, [isDark]);
  useEffect(() => { if (previewRef.current) Prism.highlightAllUnder(previewRef.current); }, [raw, lang, theme, fontSize]);

  const formatted = useMemo(() => raw.trim(), [raw]);

  // Actions
  const copyAll = async () => {
    try { await navigator.clipboard.writeText(formatted); toast.success("Copied"); }
    catch {
      const ta = document.createElement("textarea"); ta.value = formatted; document.body.appendChild(ta);
      ta.select(); document.execCommand("copy"); ta.remove(); toast.success("Copied");
    }
  };

  const downloadFile = () => {
    const blob = new Blob([formatted], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${filename || "snippet"}.${lang === "markdown" ? "md" : (lang === "html" ? "html" : lang)}`;
    document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url);
  };

  const exportPNG = async () => {
    try {
      let toPng: any; try { ({ toPng } = await import("html-to-image")); } catch { throw new Error("missing-lib"); }
      const node = exportRef.current || canvasRef.current || previewRef.current; if (!node) return;
      const rect = node.getBoundingClientRect();
      const dataUrl = await toPng(node, { pixelRatio: 2, backgroundColor: "#0b0e14", width: Math.ceil(rect.width), height: Math.ceil(rect.height) });
      const a = document.createElement("a"); a.href = dataUrl; a.download = `${filename || "snippet"}.png`; document.body.appendChild(a); a.click(); a.remove();
    } catch (e: any) {
      if (e?.message === "missing-lib") toast.error("Run: npm i html-to-image");
      else { console.error(e); toast.error("PNG export failed"); }
    }
  };

  const saveLink = async () => {
    if (!cloudUrl || !cloudKey) return toast.error("Set NEXT_PUBLIC_SUPABASE_URL/ANON_KEY to save.");
    const client = createClient(cloudUrl, cloudKey);
    const payload = { content: formatted, type: "code", lang, theme, font_size: fontSize, filename };
    const { data, error } = await client.from("documents").insert(payload).select().single();
    if (error) { toast.error(error.message); return; }
    const url = `${window.location.origin}/d/${data.id}`;
    await navigator.clipboard.writeText(url);
    toast.success("Link copied", { description: url });
  };

  return (
    <div className="h-screen grid grid-cols-[56px,1fr]">
      {/* Left rail */}
      <aside className="border-r border-[hsl(var(--border))] flex flex-col items-center gap-4 py-4">
        <button onClick={() => setMode("card")} className={cn("p-2 rounded-md hover:bg-[hsl(var(--muted))]", mode==="card" && "bg-[hsl(var(--muted))]")} title="Code Card"><Code2 size={18}/></button>
        <button onClick={() => setMode("design")} className={cn("p-2 rounded-md hover:bg-[hsl(var(--muted))]", mode==="design" && "bg-[hsl(var(--muted))]")} title="Design"><Settings2 size={18}/></button>
        <div className="mt-auto flex flex-col items-center gap-3">
          <button onClick={() => setIsDark(v => !v)} className="p-2 rounded-md hover:bg-[hsl(var(--muted))]" title="Theme">
            {isDark ? <Sun size={18}/> : <Moon size={18}/>}
          </button>
        </div>
      </aside>

      {/* Main split canvas */}
      <Split className="flex" sizes={[40,60]} minSize={280} gutterSize={10} snapOffset={0}>
        {/* Controls/Editor Panel */}
        <div className="h-full grid grid-rows-[auto,1fr]">
          {/* Controls */}
          <div className="border-b border-[hsl(var(--border))] p-3 flex items-center gap-3">
            {/* font size */}
            <div className="flex items-center gap-2">
              <span className="text-xs text-white/70">Font</span>
              <input type="range" min={12} max={22} value={fontSize} onChange={(e)=>setFontSize(parseInt(e.target.value))}/>
              <span className="text-xs tabular-nums">{fontSize}px</span>
            </div>
            {/* theme */}
            <div className="flex items-center gap-2">
              <span className="text-xs text-white/70">Theme</span>
              <select value={theme} onChange={(e)=>setTheme(e.target.value as CarbonKey)} className="bg-transparent border rounded px-2 py-1 text-xs">
                {Object.keys(CARBON_BG).map(k=>(<option key={k} value={k}>{k}</option>))}
              </select>
            </div>
            {/* language */}
            <div className="flex items-center gap-2">
              <span className="text-xs text-white/70">Lang</span>
              <input list="langs" value={lang} onChange={(e)=>setLang(e.target.value)} className="bg-transparent border rounded px-2 py-1 text-xs w-28"/>
              <datalist id="langs">{LANGUAGE_LIST.map(l=><option key={l} value={l}/>)}</datalist>
            </div>
          </div>

          {/* Editor */}
          <div className="p-3">
            <textarea
              className="w-full h-full outline-none resize-none rounded-lg bg-[hsl(var(--muted))] p-3 text-sm leading-6 font-mono"
              style={{ fontFamily: fira }}
              value={raw}
              onChange={e=>setRaw(e.target.value)}
              spellCheck={false}
            />
          </div>
        </div>

        {/* Preview Canvas */}
        <div className="h-full relative">
          {/* Top-right toolbar */}
          <div className="absolute right-3 top-3 z-20 flex items-center gap-2">
            <button className="p-2 rounded-md bg-[hsl(var(--muted))] hover:opacity-90" onClick={copyAll} title="Copy"><Copy size={16}/></button>
            <button className="p-2 rounded-md bg-[hsl(var(--muted))] hover:opacity-90" onClick={downloadFile} title="Download"><Download size={16}/></button>
            <button className="p-2 rounded-md bg-[hsl(var(--muted))] hover:opacity-90" onClick={exportPNG} title="Export PNG"><ImageIcon size={16}/></button>
            <button className="p-2 rounded-md bg-[hsl(var(--muted))] hover:opacity-90" onClick={saveLink} title="Save & Copy Link"><Share2 size={16}/></button>
          </div>

          {/* Canvas content */}
          <div ref={exportRef} className="h-full w-full overflow-auto grid place-items-center p-6">
            <div ref={canvasRef} className={`rounded-2xl p-6 shadow-card ring-1 ring-black/10 border relative overflow-hidden ${CARBON_BG[theme]} max-w-3xl w-full`}>
              <div className="absolute left-4 top-4 flex items-center gap-2 opacity-70">
                <span className="size-3 rounded-full bg-red-400" />
                <span className="size-3 rounded-full bg-yellow-400" />
                <span className="size-3 rounded-full bg-green-400" />
                <span className="ml-2 text-xs text-white/70 select-none">{filename}.{lang === "markdown" ? "md" : (lang === "html" ? "html" : lang)}</span>
              </div>
              <div ref={previewRef} className="w-full mt-6">
                <pre className={`line-numbers rounded-xl border p-5 overflow-auto bg-[#282c34] text-[#abb2bf] language-${lang}`} style={{ fontFamily: fira, fontSize }}>
                  <code className={`language-${lang}`}>{formatted}</code>
                </pre>
              </div>
            </div>
          </div>
        </div>
      </Split>

      <style jsx global>{`
        code[class*="language-"], pre[class*="language-"] {
          color: #abb2bf; background: transparent; text-shadow: none; font-family: ${fira};
        }
        .token.comment, .token.prolog, .token.doctype, .token.cdata { color: #5c6370; }
        .token.punctuation { color: #abb2bf; }
        .token.selector, .token.tag { color: #e06c75; }
        .token.property, .token.boolean, .token.number, .token.constant, .token.symbol, .token.attr-name { color: #d19a66; }
        .token.string, .token.char, .token.builtin, .token.inserted { color: #98c379; }
        .token.operator, .token.entity, .token.url { color: #56b6c2; }
        .token.atrule, .token.keyword { color: #c678dd; }
        .token.function, .token.class-name { color: #61afef; }
        .token.regex, .token.important, .token.variable { color: #e06c75; }
        .token.deleted { color: #e06c75; }
      `}</style>
    </div>
  );
}
