"use client";

import React, { useEffect, useMemo, useRef, useState } from "react";
import Split from "react-split";
import { toast } from "sonner";
import { Download, Copy, Share2, Image as ImageIcon, Settings2, Code2, Moon, Sun, Globe2, Search, Loader2 } from "lucide-react";
import Prism from "prismjs";
import "prismjs/components/prism-markup";
import "prismjs/components/prism-clike";
import "prismjs/components/prism-markup-templating";
import "prismjs/components/prism-javascript";
import "prismjs/components/prism-typescript";
import "prismjs/components/prism-tsx";
import "prismjs/components/prism-jsx";
import "prismjs/components/prism-json";
import "prismjs/components/prism-bash";
import "prismjs/components/prism-python";
import "prismjs/plugins/line-numbers/prism-line-numbers";
import "prismjs/plugins/line-numbers/prism-line-numbers.css";
import "prismjs/themes/prism-tomorrow.css";

const CARBON_BG = {
  onedark: "bg-[#282c34]",
  midnight: "bg-[#0e1116]",
  dracula: "bg-[#282a36]",
} as const;

type CarbonKey = keyof typeof CARBON_BG;

const fira = "'Fira Code', ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace";
const cn = (...a: any[]) => a.filter(Boolean).join(" ");

const LANGUAGE_LIST = ["typescript", "javascript", "python", "bash", "json", "markdown", "css", "html", "tsx", "jsx"];

const LANGUAGE_EXTENSION: Record<string, string> = {
  typescript: "ts",
  javascript: "js",
  python: "py",
  bash: "sh",
  json: "json",
  markdown: "md",
  html: "html",
  css: "css",
  tsx: "tsx",
  jsx: "jsx",
};

const langToExtension = (value: string) => LANGUAGE_EXTENSION[value] || value;

export default function CanvasPage() {
  const [isDark, setIsDark] = useState(true);
  const [mode, setMode] = useState<"card" | "design">("card");
  const [raw, setRaw] = useState(`export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};`);
  const [lang, setLang] = useState("typescript");
  const [theme, setTheme] = useState<CarbonKey>("onedark");
  const [fontSize, setFontSize] = useState(16);
  const [filename, setFilename] = useState("snippet");
  const [isPublic, setIsPublic] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");
  const [searchResults, setSearchResults] = useState<any[]>([]);
  const [searching, setSearching] = useState(false);
  const previewRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLDivElement>(null);
  const exportRef = useRef<HTMLDivElement>(null);

  useEffect(() => { document.documentElement.classList.toggle("dark", isDark); }, [isDark]);
  useEffect(() => { if (previewRef.current) Prism.highlightAllUnder(previewRef.current); }, [raw, lang, theme, fontSize]);

  const formatted = useMemo(() => raw.trim(), [raw]);
  const extension = useMemo(() => langToExtension(lang), [lang]);
  const fullFilename = useMemo(() => `${filename || "snippet"}.${extension}`, [filename, extension]);

  const copyAll = async () => {
    try { await navigator.clipboard.writeText(formatted); toast.success("Copied"); }
    catch {
      const ta = document.createElement("textarea"); ta.value = formatted; document.body.appendChild(ta);
      ta.select(); document.execCommand("copy"); ta.remove(); toast.success("Copied");
    }
  };

  const downloadFile = () => {
    const blob = new Blob([formatted], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = fullFilename;
    document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url);
  };

  const exportPNG = async () => {
    try {
      let toPng: any; try { ({ toPng } = await import("html-to-image")); } catch { throw new Error("missing-lib"); }
      const node = exportRef.current || canvasRef.current || previewRef.current; if (!node) return;
      const rect = node.getBoundingClientRect();
      const dataUrl = await toPng(node, { pixelRatio: 2, backgroundColor: "#0b0e14", width: Math.ceil(rect.width), height: Math.ceil(rect.height) });
      const a = document.createElement("a"); a.href = dataUrl; a.download = `${filename || "snippet"}.png`; document.body.appendChild(a); a.click(); a.remove();
    } catch (e: any) {
      if (e?.message === "missing-lib") toast.error("Run: npm i html-to-image");
      else { console.error(e); toast.error("PNG export failed"); }
    }
  };

  const saveLink = async () => {
    try {
      const res = await fetch("/api/doc", { method: "POST", body: JSON.stringify({
        content: formatted,
        type: "code",
        lang,
        theme,
        font_size: fontSize,
        filename: fullFilename,
        is_public: isPublic,
      }) });
      const json = await res.json();
      if (!res.ok) throw new Error(json?.error || "Unable to save snippet");
      const url = `${window.location.origin}/d/${json.id}`;
      await navigator.clipboard.writeText(url);
      toast.success("Link copied", { description: url });
    } catch (e: any) {
      toast.error(e?.message || "Share failed");
    }
  };

  const searchPublicSnippets = async () => {
    if (!searchTerm.trim()) { toast.error("Enter a keyword to search"); return; }
    setSearching(true);
    try {
      const res = await fetch(`/api/doc?search=${encodeURIComponent(searchTerm.trim())}`);
      const json = await res.json();
      if (!res.ok) throw new Error(json?.error || "Search failed");
      setSearchResults(json || []);
    } catch (e: any) {
      toast.error(e?.message || "Unable to search");
      setSearchResults([]);
    } finally {
      setSearching(false);
    }
  };

  const loadSnippet = (snippet: any) => {
    if (!snippet) return;
    setRaw(snippet.content || "");
    setLang(snippet.lang || "typescript");
    setTheme((snippet.theme as CarbonKey) || "onedark");
    setFontSize(Number(snippet.font_size) || 16);
    setFilename((snippet.filename as string)?.replace(/\.[^.]+$/, "") || "snippet");
    toast.success("Snippet loaded");
  };

  return (
    <div className="h-screen grid grid-cols-[56px,1fr]">
      <aside className="border-r border-[hsl(var(--border))] flex flex-col items-center gap-4 py-4">
        <button onClick={() => setMode("card")} className={cn("p-2 rounded-md hover:bg-[hsl(var(--muted))]", mode === "card" && "bg-[hsl(var(--muted))]")} title="Code Card"><Code2 size={18} /></button>
        <button onClick={() => setMode("design")} className={cn("p-2 rounded-md hover:bg-[hsl(var(--muted))]", mode === "design" && "bg-[hsl(var(--muted))]")} title="Settings"><Settings2 size={18} /></button>
        <div className="mt-auto flex flex-col items-center gap-3">
          <button onClick={() => setIsDark(v => !v)} className="p-2 rounded-md hover:bg-[hsl(var(--muted))]" title="Theme">
            {isDark ? <Sun size={18} /> : <Moon size={18} />}
          </button>
        </div>
      </aside>

      <Split className="flex" sizes={[40, 60]} minSize={280} gutterSize={10} snapOffset={0}>
        <div className="h-full grid grid-rows-[auto,1fr]">
          <div className="border-b border-[hsl(var(--border))] p-3 flex flex-wrap items-center gap-3">
            <div className="flex items-center gap-2">
              <span className="text-xs text-foreground/70">Font</span>
              <input type="range" min={12} max={22} value={fontSize} onChange={(e) => setFontSize(parseInt(e.target.value))} />
              <span className="text-xs tabular-nums">{fontSize}px</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-xs text-foreground/70">Theme</span>
              <select value={theme} onChange={(e) => setTheme(e.target.value as CarbonKey)} className="bg-transparent border rounded px-2 py-1 text-xs">
                {Object.keys(CARBON_BG).map(k => (<option key={k} value={k}>{k}</option>))}
              </select>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-xs text-foreground/70">Lang</span>
              <input list="langs" value={lang} onChange={(e) => setLang(e.target.value)} className="bg-transparent border rounded px-2 py-1 text-xs w-28" />
              <datalist id="langs">{LANGUAGE_LIST.map(l => <option key={l} value={l} />)}</datalist>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-xs text-foreground/70">Title</span>
              <input value={filename} onChange={(e) => setFilename(e.target.value)} className="bg-transparent border rounded px-2 py-1 text-xs w-32" placeholder="snippet" />
              <span className="text-xs text-muted-foreground">.{extension}</span>
            </div>
            <label className="flex items-center gap-2 text-xs text-foreground/80 cursor-pointer">
              <input type="checkbox" checked={isPublic} onChange={(e) => setIsPublic(e.target.checked)} />
              Make public
            </label>
          </div>

          {mode === "card" ? (
            <div className="p-3">
              <textarea
                className="w-full h-full outline-none resize-none rounded-lg bg-[hsl(var(--muted))] p-3 text-sm leading-6 font-mono"
                style={{ fontFamily: fira }}
                value={raw}
                onChange={e => setRaw(e.target.value)}
                spellCheck={false}
              />
            </div>
          ) : (
            <div className="p-4 space-y-4 overflow-auto">
              <div className="rounded-lg border p-4 bg-[hsl(var(--muted))]/40">
                <h3 className="font-semibold text-sm mb-2">Snippet settings</h3>
                <p className="text-xs text-muted-foreground">Customize your exported file name, appearance, and visibility without leaving the canvas.</p>
                <div className="mt-3 grid gap-3 sm:grid-cols-2">
                  <div className="flex flex-col gap-1">
                    <label className="text-xs text-muted-foreground">File name</label>
                    <input value={filename} onChange={(e) => setFilename(e.target.value)} className="bg-transparent border rounded px-2 py-1 text-sm" placeholder="snippet" />
                    <span className="text-[11px] text-muted-foreground">Will export as <strong>{fullFilename}</strong></span>
                  </div>
                  <div className="flex flex-col gap-1">
                    <label className="text-xs text-muted-foreground">Language extension</label>
                    <div className="text-sm font-mono bg-background border rounded px-2 py-2 flex items-center justify-between">
                      <span>{lang}</span>
                      <span className="text-muted-foreground">.{extension}</span>
                    </div>
                    <span className="text-[11px] text-muted-foreground">Downloads use the correct extension automatically.</span>
                  </div>
                  <div className="flex flex-col gap-1">
                    <label className="text-xs text-muted-foreground">Font size</label>
                    <input type="range" min={12} max={22} value={fontSize} onChange={(e) => setFontSize(parseInt(e.target.value))} />
                    <span className="text-[11px] text-muted-foreground">Previewed at {fontSize}px</span>
                  </div>
                  <div className="flex items-center gap-3 mt-1">
                    <label className="text-xs text-muted-foreground">Public library</label>
                    <label className="flex items-center gap-2 text-xs text-foreground/80 cursor-pointer">
                      <input type="checkbox" checked={isPublic} onChange={(e) => setIsPublic(e.target.checked)} />
                      Publish snippet when sharing
                    </label>
                  </div>
                </div>
              </div>

              <div className="rounded-lg border p-4 bg-[hsl(var(--muted))]/40">
                <h3 className="font-semibold text-sm mb-2 flex items-center gap-2"><Globe2 size={16} />Search public snippets</h3>
                <div className="flex flex-col gap-2">
                  <div className="flex flex-wrap gap-2">
                    <input value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} placeholder="Search by title or content" className="flex-1 min-w-[160px] bg-transparent border rounded px-3 py-2 text-sm" />
                    <button onClick={searchPublicSnippets} className="inline-flex items-center gap-2 bg-primary text-primary-foreground px-3 py-2 rounded text-sm">
                      {searching ? <Loader2 size={14} className="animate-spin" /> : <Search size={14} />}<span>Search</span>
                    </button>
                  </div>
                  <div className="max-h-48 overflow-auto space-y-2">
                    {searchResults.length === 0 && <div className="text-xs text-muted-foreground">No public snippets yet.</div>}
                    {searchResults.map((item) => (
                      <div key={item.id} className="rounded border bg-background/60 px-3 py-2 flex items-center justify-between gap-3">
                        <div className="flex-1 min-w-0">
                          <div className="text-sm font-semibold truncate">{item.filename || "Untitled"}</div>
                          <div className="text-[11px] text-muted-foreground truncate">{item.lang} • {item.theme}</div>
                        </div>
                        <div className="flex items-center gap-2">
                          <button className="text-xs underline" onClick={() => loadSnippet(item)}>Load</button>
                          <button className="text-xs underline" onClick={() => navigator.clipboard.writeText(`${window.location.origin}/d/${item.id}`).then(() => toast.success("Link copied"))}>Copy link</button>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>

        <div className="h-full relative">
          <div className="absolute right-3 top-3 z-20 flex items-center gap-2">
            <button className="p-2 rounded-md bg-[hsl(var(--muted))] hover:opacity-90" onClick={copyAll} title="Copy"><Copy size={16} /></button>
            <button className="p-2 rounded-md bg-[hsl(var(--muted))] hover:opacity-90" onClick={downloadFile} title="Download"><Download size={16} /></button>
            <button className="p-2 rounded-md bg-[hsl(var(--muted))] hover:opacity-90" onClick={exportPNG} title="Export PNG"><ImageIcon size={16} /></button>
            <button className="p-2 rounded-md bg-[hsl(var(--muted))] hover:opacity-90" onClick={saveLink} title="Save & Copy Link"><Share2 size={16} /></button>
          </div>

          <div ref={exportRef} className="h-full w-full overflow-auto grid place-items-center p-6">
            <div ref={canvasRef} className={`rounded-2xl p-6 shadow-card ring-1 ring-black/10 border relative overflow-hidden ${CARBON_BG[theme]} max-w-3xl w-full`}>
              <div className="absolute left-4 top-4 opacity-90">
                <span className="ml-2 text-xs text-white/90 select-none bg-black/30 px-2 py-1 rounded">{fullFilename}</span>
              </div>
              <div ref={previewRef} className="w-full mt-10">
                <pre className={`line-numbers rounded-xl border p-5 overflow-auto bg-[#282c34] text-[#abb2bf] language-${lang}`} style={{ fontFamily: fira, fontSize }}>
                  <code className={`language-${lang}`}>{formatted}</code>
                </pre>
              </div>
            </div>
          </div>
        </div>
      </Split>

      <style jsx global>{`
        code[class*="language-"], pre[class*="language-"] {
          color: #abb2bf; background: transparent; text-shadow: none; font-family: ${fira};
        }
        .token.comment, .token.prolog, .token.doctype, .token.cdata { color: #5c6370; }
        .token.punctuation { color: #abb2bf; }
        .token.selector, .token.tag { color: #e06c75; }
        .token.property, .token.boolean, .token.number, .token.constant, .token.symbol, .token.attr-name { color: #d19a66; }
        .token.string, .token.char, .token.builtin, .token.inserted { color: #98c379; }
        .token.operator, .token.entity, .token.url { color: #56b6c2; }
        .token.atrule, .token.keyword { color: #c678dd; }
        .token.function, .token.class-name { color: #61afef; }
        .token.regex, .token.important, .token.variable { color: #e06c75; }
        .token.deleted { color: #e06c75; }
      `}</style>
    </div>
  );
}
